baseURL = "https://blog-labveilletech.meryl-dubois.ch"
languageCode = "fr-ch"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Labo de veille technologique"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@zerostaticio"
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addDot = true
  addFrame = false
  highlightColor = '#6699cc'
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  headingColor = "#1c1b1d"
  textColor = "#4e5157"
  dotColor = "#6699cc"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'accueil'
    name = 'Accueil'
    url = '/'
    weight = 1

